name: 'Repo setup'
description: 'Checkout, cache, install deps (Node, Python, Docker layers), etc.'

inputs:
  web_port:
    description: 'PORT for web preview'
    required: true

  mysql_root_password:
    description: 'MySQL root password'
    required: true

  mysql_database:
    description: 'MySQL database name'
    required: true

  jwt_secret_key:
    description: 'JWT secret key'
    required: true

  aws_access_key_id:
    description: 'AWS access key ID'
    required: true

  aws_secret_access_key:
    description: 'AWS secret access key'
    required: true

  access_packages_pat:
    description: 'GitHub Packages PAT for npm install'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Get secrets
      shell: bash
      run: |
        mkdir tokens
        echo "MYSQL_ROOT_PASSWORD=${{ inputs.mysql_root_password }}" > tokens/.env
        echo "MYSQL_DATABASE=${{ inputs.mysql_database }}"        >> tokens/.env
        echo "JWT_SECRET_KEY=${{ inputs.jwt_secret_key }}"        >> tokens/.env
        echo "AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }}" >> tokens/.env
        echo "AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }}"          >> tokens/.env

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ hashFiles('**/*Dockerfile','**/.dockerignore','**/requirements.txt','**/web/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Cache Node.js dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          ./web/.node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('web/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Node.js dependencies
      shell: bash
      working-directory: ./web
      run: |
        # set the scope registry (safe to commit this line in repo if you want)
        echo "@srlstars:registry=https://npm.pkg.github.com" > .npmrc
        echo "always-auth=true" >> .npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ inputs.access_packages_pat }}" > ~/.npmrc
        npm ci

    - name: Set up Python & cache pip
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'

    - name: Install Python packages (including behave)
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('web/package-lock.json', 'requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Install Playwright browsers (npm)
      shell: bash
      working-directory: ./web
      run: npx playwright install --with-deps

    - name: Install Playwright browsers (Python for behave)
      shell: bash
      run: playwright install chromium
